# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9ba0d1bcb3937bd36b926628c0e5e3fbdbf7cb0f2ca74bafaa0ee92d2f5b6e86c22a854c84027f482359e9095bd5780e08df7ac5157a7dba40301d5d45350ea

test:
  secret_key_base: bcdb492aa9cac79374b2b4bf9173840b6f0222f8fde34f879c86a5119c6a1e202792ce4220aec71087636a134b9551600d1c41c0963a0a3299d4fcb082ee450f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
