version: "3.4"

services:
  active-record:
    build:
      context: ./active-record
      dockerfile: ../Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3001:3000
    volumes:
      - ./active-record:/usr/src/service
    #stdin_open: true

  active-remote:
    build:
      context: ./active-remote
      dockerfile: ../Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3002:3000
    volumes:
      - ./active-remote:/usr/src/service
    #stdin_open: true

  nats:
    image: nats:latest
    #ports:
    #  - 4222:4222
    #  - 8222:8222
    #stdin_open: true
  busybox:
    image: busybox:latest
    stdin_open: true
